root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[runner]
cmd = "go run ./cmd/tarot-admin-app/main.go"

[watch]
dirs = ["."]
files = ["**/*.go", "**/*.tmpl", "**/*.templ"]
exclude = ["vendor", "node_modules"]

[build]
cmd = "go build -o ./tmp/admin-main.exe ./cmd/tarot-admin-app/main.go"
bin = "./tmp/admin-main.exe"  # Correct the path format and point to the correct binary
delay = 1000
exclude_dir = ["assets", "tmp", "vendor", "testdata"]
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = false
follow_symlink = false
poll = false

[color]
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
time = false

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = false
keep_scroll = true
